Made the API to count the total no. of files
codelitdev/medialit pull request #78
Opened 2024-01-20 09:05 UTC by RaviRajput10

fixes: #77

2024-01-20 13:56 UTC, rajat1saxena requested changes

2024-01-20 13:56 UTC, rajat1saxena commented on apps/api/lib/media/handlers.ts
> +        const userId = req.user._id;
Move these two lines of out of `try`.

2024-01-21 14:43 UTC, RaviRajput10 commented on apps/api/lib/media/handlers.ts
> +        const userId = req.user._id;
Moved up the lines.

2024-01-22 15:34 UTC, rajat1saxena commented
If I remove `?page=1` from the URL, the pagination breaks.

Ideally, if the page number is not provided, it is automatically added to the URL. 

![image](https://github.com/codelitdev/medialit/assets/821092/d530b088-44d0-4a52-a924-e2324cde9132)

2024-01-22 17:43 UTC, RaviRajput10 commented
> If I remove `?page=1` from the URL, the pagination breaks.
> 
> Ideally, if the page number is not provided, it is automatically added to the URL.
> 
> ![image](https://private-user-images.githubusercontent.com/821092/298636651-d530b088-44d0-4a52-a924-e2324cde9132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDQwNzYsIm5iZiI6MTcwNTk0Mzc3NiwicGF0aCI6Ii84MjEwOTIvMjk4NjM2NjUxLWQ1MzBiMDg4LTQ0ZDAtNGE1Mi1hOTI0LWUyMzI0Y2RlOTEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxNzE2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTBhYzRiNDYwMmMxYmRhMzMwOGNiMWZhZTlhNTNiYWZiOTk5ZmEyN2VmYjNhNTc4MjlhMTQ1NTVhZjY1ZDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ix1IsbL9P4XFvHvMiIcEAonfRAAk3d2328bDSE92e9M)

2024-01-24 10:02 UTC, merged